---
title: "DBS Effects: Perceptual Data Analysis"
---

# Packages
```{r}
library(tidyverse) # install.packages("rlang")
library(lmerTest) # install.packages("lmerTest")
library(performance) # install.packages("performance")
```

# Load the Data
```{r}
speakerList <- rio::import("DBS data/Project Progress - Speakers.csv") %>%
  dplyr::rename(DBS_Status = 3) %>%
  dplyr::mutate(Sex = as.factor(Sex),
                Group = as.factor(Group),
                Speaker = as.factor(Speaker),
                DBS_Status = as.factor(DBS_Status))

SpeakerSex <- speakerList |>
  dplyr::select(Speaker, Sex) |>
  unique()

listenerRatings <- rio::import(file = "Prepped Data/Perceptual Data/Listener Ratings.csv") |>
  dplyr::mutate(ListenerID = as.factor(ListenerID),
                Speaker = as.factor(Speaker),
                Group = as.factor(Group),
                DBS_Status = as.factor(DBS_Status),
                ratingType = as.factor(ratingType))

listenerRatings_wide <- listenerRatings |>
  dplyr::select(!Rel_Rating) |>
  tidyr::pivot_wider(names_from = ratingType,
                     values_from = Rating) %>%
  base::merge(., SpeakerSex)

dir.create("Figures/Perceptual Plots", showWarnings = F)
dir.create("Figures/Perceptual Plots/Raw", showWarnings = F)
dir.create("Figures/Perceptual Plots/Z", showWarnings = F)
```
## Boxplot function
```{r}
perceptual_BoxPlot <- function(data, ylabel, norm){
  plotData <- data |>
     dplyr::mutate(PlotGroup = paste(Group,DBS_Status),
                PlotGroup = gsub(" ", "", PlotGroup),
                PlotGroup = gsub("_", "-", PlotGroup),
                PlotGroup = gsub("DBSOn", "DBS On", PlotGroup, ignore.case = T),
                PlotGroup = gsub("DBSOff", "DBS Off", PlotGroup, ignore.case = T),
                PlotGroup = factor(PlotGroup, levels = c("HC", "PD", "PD-DBS Off","PD-DBS On")))
  if(norm == TRUE) {
    plotData <- plotData |>
      dplyr::group_by(Speaker) |>
      dplyr::mutate(Rating = scale(Rating)) |>
      dplyr::ungroup()
  }
  
  # Colors
  my_pal <- c("#5fbf7d", "#276fbf", "#c658b2", "#892f78")
  
  bp <- ggplot(data = plotData) +
    aes(x = PlotGroup,
        y = Rating,
        color = PlotGroup,
        fill = PlotGroup) +
    geom_boxplot(alpha = .5) +
    labs(x = element_blank(), y = ylabel) +
    theme_classic() +
    theme(legend.title = element_blank(),
          axis.text.x = element_blank(),
          axis.ticks.x = element_blank()) +
    scale_color_manual(values = my_pal) +
    scale_fill_manual(values = my_pal)
  
  return(bp)
}
```
## Pairwise Table
```{r}
pairwiseTable_t <- function(emmsPair) {
    summary_table <- summary(emmsPair, infer = TRUE) %>%
      #dplyr::filter(contrast != "Off - On") %>%
      dplyr::mutate_at(.vars = c(
        "estimate",
        "SE",
        "lower.CL",
        "upper.CL",
        "t.ratio"),
        .funs = round,
        digits = 2) %>%
    dplyr::mutate(p.value = round(p.value, digits = 3),
                  p.value = ifelse(p.value < .001,"<.001",p.value),
                  CI = paste(lower.CL,upper.CL, sep = " - ")) %>%
      dplyr::select(!lower.CL:upper.CL)
    
    return(summary_table)
}
```

# 0. All Ratings
```{r}
modelData <- listenerRatings %>%
  dplyr::filter(Group == "PD_DBS")
```

## Models
M0
```{r}
ratings_m0 <- lmerTest::lmer(Rating ~ 1 + (1|Speaker) + (1|ListenerID), data = modelData)
summary(ratings_m0)

performance::icc(ratings_m0)
```
M1
```{r}
ratings_m1 <- lmerTest::lmer(Rating ~ 1 + ratingType +
                               (1|Speaker) +
                               (1|ListenerID),
                             data = modelData)
summary(ratings_m1)

performance::check_model(ratings_m1)
performance::check_singularity(ratings_m1)

anova(ratings_m0, ratings_m1)
```
M2
```{r}
ratings_m2 <- lmerTest::lmer(Rating ~ 1 + ratingType*DBS_Status +
                               (1|Speaker) +
                               (1|ListenerID),
                             data = modelData)
summary(ratings_m2)

performance::check_model(ratings_m2)
performance::check_singularity(ratings_m2)

anova(ratings_m1, ratings_m2)
```
```{r}
# Load the required package
library(emmeans)

# Create the emmeans object
emms <- emmeans(ratings_m2, ~ DBS_Status | ratingType)

# Perform pairwise comparisons
pairwise <- pairs(emms)

# Display the pairwise comparisons
summary(pairwise)

```

## Pairwise Table
```{r}
ratingsAvg <- listenerRatings %>%
  dplyr::filter(Group == "PD_DBS") %>%
  dplyr::group_by(ratingType, DBS_Status) %>%
  dplyr::summarise(M = mean(Rating, na.rm = T),
                   SD = sd(Rating, na.rm = T)) %>%
  tidyr::pivot_wider(id_cols = c(ratingType),
                     names_from = DBS_Status,
                     values_from = c(M, SD))

pairwiseTable_t(pairs(emms)) %>%
  dplyr::select(ratingType, contrast, estimate, CI, p.value) %>%
  base::merge(., ratingsAvg) %>%
  dplyr::relocate(M_Off:SD_On, .after = ratingType) %>%
  dplyr::rename(Measure = ratingType,
                Contrast = contrast,
                Estimate = estimate,
                p = p.value) %>%
  dplyr::mutate(Measure = factor(Measure,
                                 levels = c(
                                   "Int",
                                   "LE",
                                   "AP",
                                   "VQ",
                                   "Pro"
                                 ),
                                 labels = c(
                                   "Intelligibility",
                                   "Listening Effort",
                                   "Articulatory Precision",
                                   "Voice Quality",
                                   "Prosody"
                                 ))) %>%
  dplyr::mutate_at(.vars = c("M_Off",
                             "SD_Off",
                             "M_On",
                             "SD_On"),
                   .funs = round, digits = 2) %>%
  dplyr::arrange(Measure) %>%
  gt::gt() %>%
  gt::tab_spanner(
    columns = c(M_Off, SD_Off),
    label = "DBS Off") %>%
  gt::tab_spanner(
    columns = c(M_On, SD_On),
    label = "DBS On") %>%
  gt::cols_label(
    M_Off = "M",
    SD_Off = "SD",
    M_On = "M",
    SD_On = "SD"
  ) %>%
  gt::gtsave(filename = "Perceptual Pairwise Comparisons.html",
             path = "Tables")
```

# All Perceptual Measures
```{r}
plotData <- listenerRatings_wide %>%
  dplyr::group_by(Speaker, Sex, Group, DBS_Status) %>%
  dplyr::summarise(AP = mean(AP, na.rm = T),
                   Int = mean(Int, na.rm = T),
                   LE = mean(LE, na.rm = T),
                   Pro = mean(Pro, na.rm = T),
                   VQ = mean(VQ, na.rm = T)) %>%
  dplyr::ungroup() %>%
  dplyr::mutate(Speaker = factor(Speaker,
                                 levels = c(
                                   "PDDBS1",
                                   "PDDBS2",
                                   "PDDBS4",
                                   "PDDBS5",
                                   "PDDBS6",
                                   "PDDBS7",
                                   "PDDBS8",
                                   "PDDBS9",
                                   "PDDBS11"
                                   ),
                                 labels = c(
                                   "PD-DBS1",
                                   "PD-DBS2",
                                   "PD-DBS4",
                                   "PD-DBS5",
                                   "PD-DBS6",
                                   "PD-DBS7",
                                   "PD-DBS8",
                                   "PD-DBS9",
                                   "PD-DBS11"
                                 ))) %>%
  dplyr::filter(Group == "PD_DBS") %>%
  dplyr::group_by(Speaker,Sex,DBS_Status) %>%
  dplyr::summarise(Int = mean(Int, na.rm = T),
                   AP = mean(AP, na.rm = T),
                   LE = mean(LE, na.rm = T),
                   Pro = mean(Pro, na.rm = T),
                   VQ = mean(VQ, na.rm = T)) %>%
  tidyr::pivot_longer(cols = Int:VQ,
                      names_to = "Measure",
                      values_to = "Value") %>%
  dplyr::mutate(Measure = factor(Measure,
                                 levels = c(
                                   "Int",
                                   "AP",
                                   "LE",
                                   "VQ",
                                   "Pro"
                                 ),
                                 labels = c(
                                   "Intelligibility",
                                   "Articulatory Precision",
                                   "Listening Effort",
                                   "Voice Quality",
                                   "Prosody"
                                   )),
                label = gsub("[^0-9.-]", "", Speaker),
                label = gsub("-", "", label))


pointSize <- 3
plot <- plotData %>%
  ggplot() +
  aes(x = DBS_Status,
      y = Value,
      group = Speaker) +
  
  # Plotting the line
  geom_line(
    color = "black",
    linetype = "longdash",
    position = position_dodge(width = 0.3)) +
  
  # Plotting the points, color by Speaker
  geom_point(
    size = pointSize,
    position = position_dodge(width = 0.3)) +

  # Labels
  geom_text(aes(label = label),
            color = "white",
            size = 2,
            fontface = "bold",
    position = position_dodge(width = 0.3)) +
  
  # Mean line
  geom_smooth(method = "lm",
              show.legend = T,
              se = F,
              inherit.aes = F,
              aes(x = DBS_Status,
                  y = Value,
                  group = Measure)) +
  
  # Scaling & fixing the theme
  labs(x = "DBS Status",
       y = "") +
  
  # Wrap by Measure
  facet_wrap(~Measure, scales = "free_y") +
  
  theme_classic() +
  theme(aspect.ratio = 1)

plot

ggsave(filename = "Figures/Perceptual Measures.png",
       plot = plot,
       height = 4,
       width = 6,
       units = "in",
       scale = 1.2)
```



```{r}
perceptualDifferences <- plotData %>%
  tidyr::pivot_wider(names_from = DBS_Status,
                     values_from = Value) %>%
  dplyr::mutate(Diff = On - Off)
```

# Table
```{r}
  
SpeakerSex <- rio::import("DBS data/Project Progress - Speakers.csv") %>%
  dplyr::rename(DBS_Status = 3) %>%
  dplyr::mutate(Sex = as.factor(Sex),
                Group = as.factor(Group),
                Speaker = as.factor(Speaker),
                DBS_Status = as.factor(DBS_Status)) |>
  dplyr::select(Speaker, Sex) |>
  unique()

listenerRatings <- listenerRatings |>
    base::merge(SpeakerSex)

tableData <- rbind(listenerRatings, listenerRatings |> dplyr::mutate(Sex = "allSpeakers")) |>
  dplyr::mutate(Sex = as.factor(Sex),
                Rating = as.numeric(Rating))

TEST <- tableData |>
  dplyr::group_by(Group, Sex, DBS_Status, ratingType) |>
  dplyr::summarise(m = mean(Rating, na.rm = T),
                   sd = sd(Rating, na.rm = T)) |>
  dplyr::ungroup() |>
  dplyr::mutate(tableGroup = paste(Group,DBS_Status),
                tableGroup = gsub(" ", "", tableGroup),
                tableGroup = gsub("_", "-", tableGroup),
                tableGroup = gsub("DBSOn", "DBS_On", tableGroup),
                tableGroup = gsub("DBSOff", "DBS_Off", tableGroup),
                tableGroup = as.factor(tableGroup)) |>
  dplyr::select(tableGroup, Sex,ratingType, m, sd) |>
  tidyr::pivot_wider(id_cols = Sex:ratingType,
                     names_from = tableGroup,
                     values_from = m:sd) |>
  dplyr::select(Sex, ratingType,
                m_HC,sd_HC,
                m_PD, sd_PD,
                `m_PD-DBS_Off`, `sd_PD-DBS_Off`,
                `m_PD-DBS_On`, `sd_PD-DBS_On`) |>
  dplyr::mutate(ratingType = factor(ratingType, levels = c("Int",
                                                           "LE",
                                                           "AP",
                                                           "VQ",
                                                           "Pro"))) |>
  arrange(ratingType) |>
  dplyr::mutate(
    ratingType = case_when(
      ratingType == "AP" ~ "Articulatory Precision (%)",
      ratingType == "Int" ~ "Intelligibility (%)",
      ratingType == "LE" ~ "Listening Effort (%)",
      ratingType == "Pro" ~ "Prosody (%)",
      ratingType == "VQ" ~ "Voice Quality (%)"
    ),
    Sex = case_when(
      Sex == "F" ~ "Female Speakers",
      Sex == "M" ~ "Male Speakers",
      Sex == "allSpeakers" ~ "All Speakers"
    )
  ) |>
  gt::gt(
    rowname_col = "ratingType",
    groupname_col = "Sex"
  ) %>%
  gt::fmt_number(
    columns = 3:10,
    decimals = 2
  ) |>
  gt::tab_spanner(
    label = "HC",
    columns = c(m_HC,sd_HC),
    level = 2
    ) |>
  gt::tab_spanner(
    label = "PD",
    columns = c(m_PD,sd_PD),
    level = 2
    ) |>
  gt::tab_spanner(
    label = "Off",
    columns = c(`m_PD-DBS_Off`,`sd_PD-DBS_Off`),
    level = 1
    ) |>
  gt::tab_spanner(
    label = "On",
    columns = c(`m_PD-DBS_On`,`sd_PD-DBS_On`),
    level = 1
    ) |>
  gt::tab_spanner(
    label = "PD-DBS",
    columns = c(`m_PD-DBS_On`,`sd_PD-DBS_On`,`m_PD-DBS_Off`,`sd_PD-DBS_Off`),
    level = 2
    ) |>
  gt::cols_label(
    m_HC = "M",
    m_PD = "M",
    `m_PD-DBS_Off` = "M",
    `m_PD-DBS_On` = "M",
    sd_HC = "SD",
    sd_PD = "SD",
    `sd_PD-DBS_Off` = "SD",
    `sd_PD-DBS_On` = "SD",
  ) |>
  gt::row_group_order(groups = c("All Speakers",
                             "Female Speakers",
                             "Male Speakers")) |>
  gt::gtsave(filename = "Tables/Perceptual Descriptives.docx")

```
# Model Table
```{r}
library(sjPlot)

sjPlot::tab_model(
  Int_m1,
  LE_m1,
  VQ_m1,
  AP_m1,
  Pro_m1,
  show.reflvl = T,
  file = "Tables/Perceptual Model Output.html"
)

```

